"""Probando a cambiar partes del esquema del usuario, username, y Unique

Revision ID: 538be77e1c82
Revises: 88d1a79613a3
Create Date: 2026-03-16 00:14:16.867597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538be77e1c82'
down_revision = '88d1a79613a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=80), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)
        batch_op.create_unique_constraint('UsernameSurname_uix', ['username', 'surname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('UsernameSurname_uix', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=1)
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
