"""Migración del esquema para añadir las 2 anchuras de las cubiertas

Revision ID: 6129dc7f40d1
Revises: 60ae4f5c4dda
Create Date: 2026-04-07 17:35:50.295707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6129dc7f40d1'
down_revision = '60ae4f5c4dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tire_width_front', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('tire_width_rear', sa.Float(), nullable=False))
        batch_op.drop_column('tire_width')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tire_width', sa.FLOAT(), nullable=False))
        batch_op.drop_column('tire_width_rear')
        batch_op.drop_column('tire_width_front')

    # ### end Alembic commands ###
