"""add analyses table

Revision ID: 6e360673965a
Revises: c3ef91e6ebc1
Create Date: 2026-03-30 19:34:16.262686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e360673965a'
down_revision = 'c3ef91e6ebc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rider_weight', sa.Float(), nullable=False),
    sa.Column('bike_weight', sa.Float(), nullable=False),
    sa.Column('tire_width', sa.Float(), nullable=False),
    sa.Column('inner_rim_width', sa.Float(), nullable=False),
    sa.Column('wheel_diameter', sa.Integer(), nullable=False),
    sa.Column('tire_casing', sa.String(length=50), nullable=False),
    sa.Column('ride_style', sa.String(length=50), nullable=False),
    sa.Column('rim_type', sa.String(length=50), nullable=False),
    sa.Column('surface', sa.String(length=50), nullable=False),
    sa.Column('front_bar', sa.Float(), nullable=False),
    sa.Column('front_psi', sa.Float(), nullable=False),
    sa.Column('rear_bar', sa.Float(), nullable=False),
    sa.Column('rear_psi', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_user_id'))

    op.drop_table('analyses')
    # ### end Alembic commands ###
