"""Pequeña migración

Revision ID: 76007cfd812f
Revises: 538be77e1c82
Create Date: 2026-03-16 17:48:04.282959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76007cfd812f'
down_revision = '538be77e1c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_id', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint('uq_users_alternative_id', ['alternative_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_alternative_id', type_='unique')
        batch_op.drop_column('alternative_id')

    # ### end Alembic commands ###
