"""Añadiendo server_default, con la consulta necesaria para así no romper la integridad en la db aunque añadiré otra capa con EABYL

Revision ID: 989e728163a2
Revises: aab03aa90ca5
Create Date: 2026-07-20 13:39:58.546390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989e728163a2'
down_revision = 'aab03aa90ca5'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("UPDATE users SET session_version = 0 WHERE session_version IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('session_version',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('session_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)

    # ### end Alembic commands ###
