"""Temp de rodadura añadida

Revision ID: a09ec83c878d
Revises: cc05bb2db367
Create Date: 2026-04-07 23:47:21.323879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09ec83c878d'
down_revision = 'cc05bb2db367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_exterior', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('temp_exterior')

    # ### end Alembic commands ###
