"""Importante columna de session_version añadida de momento con valor nulo pasible, para integridad con los datos existentes

Revision ID: aab03aa90ca5
Revises: a09ec83c878d
Create Date: 2026-07-15 20:12:10.087550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab03aa90ca5'
down_revision = 'a09ec83c878d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_version')

    # ### end Alembic commands ###
